// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsmmFLHlxj7gdvcAd9T9dov1aNmWes4To',
    appId: '1:801167291160:web:dbbd1e3b077df2c9f8e46d',
    messagingSenderId: '801167291160',
    projectId: 'mirathapp-b7a10',
    authDomain: 'mirathapp-b7a10.firebaseapp.com',
    storageBucket: 'mirathapp-b7a10.firebasestorage.app',
    measurementId: 'G-9F641530QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44sTRLFbI92NSze_kaVNCwiIFgB8VZf4',
    appId: '1:801167291160:android:ef49015cfceb9bf4f8e46d',
    messagingSenderId: '801167291160',
    projectId: 'mirathapp-b7a10',
    storageBucket: 'mirathapp-b7a10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAwm02YLASwzwt2jil8YugAtvHTtawZU',
    appId: '1:801167291160:ios:fee36738952a5a9ef8e46d',
    messagingSenderId: '801167291160',
    projectId: 'mirathapp-b7a10',
    storageBucket: 'mirathapp-b7a10.firebasestorage.app',
    iosBundleId: 'com.example.mirath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAwm02YLASwzwt2jil8YugAtvHTtawZU',
    appId: '1:801167291160:ios:fee36738952a5a9ef8e46d',
    messagingSenderId: '801167291160',
    projectId: 'mirathapp-b7a10',
    storageBucket: 'mirathapp-b7a10.firebasestorage.app',
    iosBundleId: 'com.example.mirath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsmmFLHlxj7gdvcAd9T9dov1aNmWes4To',
    appId: '1:801167291160:web:db791d6e48683a19f8e46d',
    messagingSenderId: '801167291160',
    projectId: 'mirathapp-b7a10',
    authDomain: 'mirathapp-b7a10.firebaseapp.com',
    storageBucket: 'mirathapp-b7a10.firebasestorage.app',
    measurementId: 'G-0NF757CTQN',
  );
}
